### ISSUE TITLE
Visualizing the sub-design tree of a popupcad file

### ISSUE THREAD

**Issue by zhiernteoh** [popupcad/popupcad#101]
Is there a way to visualize the entire sub-design tree of a cad file?

I am trying to track which file I need to rebuild to update my design.

Thanks

**Comment by danaukes** [comment]
nothing gui based at this point, though that is a good idea.  My
visualizations I've created have been from scripts located in
popupcad/api_examples.  requires you to install a couple other packages but
it is a great idea because it will search through your files and build a
pdf of them or plot them.

On Wed, Apr 6, 2016 at 3:22 PM, zhiernteoh <notifications@github.com> wrote:

> Is there a way to visualize the entire sub-design tree of a cad file?
>
> I am trying to track which file I need to rebuild to update my design.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/101>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University

**Comment by danaukes** [comment]
I just updated design_file_connections.py to be a little bit more flexible in its use.  you can run it from the command line and just supply a file or directory you want it to scan through and it will create a pdf of the file hierarchy.
