### ISSUE TITLE
option to import yaml in sketch tool missing

### ISSUE THREAD

**Issue by zhiernteoh** [popupcad/popupcad#99]

**Comment by zhiernteoh** [comment]
problem is in popupcad for mac

**Comment by danaukes** [comment]
I need more information than this; there is also going to be a lag on any mac development.  I suggest using the windows executible if you don't want to get into the code yourself.

**Comment by braraki** [comment]
I have this problem on Mac too. I've attached a picture of the window. You can see that at the top of the window there is no bar for drop down menus. I've attached a smaller screenshot of the PC version for comparison.

![screen shot 2016-04-04 at 9 14 28 pm](https://cloud.githubusercontent.com/assets/730599/14268567/6f7c7e5e-faaa-11e5-953f-623fcbcd9caf.png)

![screen shot 2016-04-04 at 9 16 37 pm](https://cloud.githubusercontent.com/assets/730599/14268594/a8c735d2-faaa-11e5-94c5-a0ad36a9abc4.png)

**Comment by danaukes** [comment]
I don't have a mac in my lab yet; this problem will not get solved in the
meantime.  Please try to use the windows version in the meantime.  Sorry
for the lack of support at this time,

Dan

On Mon, Apr 4, 2016 at 6:17 PM, braraki <notifications@github.com> wrote:

> I have this problem on Mac too. I've attached a picture of the window. You
> can see that at the top of the window there is no bar for drop down menus.
> I've attached a smaller screenshot of the PC version for comparison.
>
> [image: screen shot 2016-04-04 at 9 14 28 pm]
> <https://cloud.githubusercontent.com/assets/730599/14268567/6f7c7e5e-faaa-11e5-953f-623fcbcd9caf.png>
>
> [image: screen shot 2016-04-04 at 9 16 37 pm]
> <https://cloud.githubusercontent.com/assets/730599/14268594/a8c735d2-faaa-11e5-94c5-a0ad36a9abc4.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/99#issuecomment-205574860>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University

**Comment by danaukes** [comment]
Remember in mac that the file menu does not travel with the window but is along the top of the screen.  

I updated the install instructions for mac to use qt instead of pyside.  Please follow [these instructions](http://www.popupcad.org/docs/mac-anaconda-setup/) to first remove your current popupcad environment(at the bottom of the page) and then reinstall it to take advantage of the new install.  

Since this new install uses pyqt instead of pyside, please switch your git branch to the pyqt4_only branch.

{% highlight bash %}
git checkout -t origin/pyqt4_only
git pull
git reset --hard
{% endhighlight %}
